import type { Metadata } from 'next';
import { Jua } from 'next/font/google';
import Providers from '@/providers';
import RootHeader from '@/app/components/RootHeader';
import './global.css';
import LeftNavigationLayout from '@/app/components/layout/LeftNavigationLayout';

const jua = Jua({
  variable: '--font-jua',
  weight: ['400'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" style={{ colorScheme: 'light' }}>
      <body className={`${jua.className}`}>
        <Providers>
          <RootHeader />
          <LeftNavigationLayout />
          <main className={'ps-[var(--nav-width)] pt-[var(--header-height)]'}>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
