import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import Providers from '@/providers';
import RootHeader from '@/app/components/RootHeader';
import './global.css';
import CategoryNavigation from '@/app/components/navigation/CategoryNavigation';
import { NotionStoreProvider } from '@/app/stores/notion-store-provider';
import CategoryNavigationLayout from '@/app/components/navigation/CategoryNavigationLayout';

const jua = Open_Sans({
  variable: '--font-jua',
  weight: ['400', '500', '600', '700', '800'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" style={{ colorScheme: 'light' }}>
      <body className={`${jua.className}`}>
        <Providers>
          <NotionStoreProvider>
            <RootHeader />
            <CategoryNavigationLayout>
              <CategoryNavigation />
            </CategoryNavigationLayout>
            <main
              className={
                'w-full h-full lg:ps-[var(--side-nav-width)] pt-[var(--header-height)]'
              }
            >
              {children}
            </main>
          </NotionStoreProvider>
        </Providers>
      </body>
    </html>
  );
}
