import type { Metadata } from 'next';
import { Work_Sans } from 'next/font/google';
import Providers from '@/providers';
// import localFont from 'next/font/local';

// const geistSans = localFont({
//   src: './fonts/GeistVF.woff',
//   variable: '--font-geist-sans',
//   weight: '100 900',
// });
// const geistMono = localFont({
//   src: './fonts/GeistMonoVF.woff',
//   variable: '--font-geist-mono',
//   weight: '100 900',
// });

const workSans = Work_Sans({
  variable: '--font-work-sans',
  weight: ['100', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" style={{ colorScheme: 'light' }} data-theme="light">
      <body className={`${workSans.variable}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
